### ISSUE TITLE
onTokens triggered but token list is undefined

### ISSUE THREAD

**Issue by dragons3232** [react-keycloak/react-native-keycloak#56] opened 2021-09-13 04:26 UTC
**Describe the bug**
Hi Keycloak team, thank you very much for providing this library. I could login using keycloak account, so it worked. I only have an issue with empty token. My problem is as below:

I am implementing keycloak auth for react native app. And I am having problem with onTokens giving empty token list. Even thought onEvent was triggered with onAuthSuccess

Here is my keycloak client
```
import { RNKeycloak } from '@react-keycloak/native';
 
const keycloak = new RNKeycloak({
  url: 'https://MYDOMAIN/auth',
  realm: 'MYREALM',
  clientId: 'account',
});

export default keycloak;
```

Implemented keycloak provider in root top App as below

```
<ReactNativeKeycloakProvider
			authClient={keycloak}
			initOptions={{
				redirectUri: 'MYAPP://auth',
				inAppBrowserOptions: {},
			}}
			onEvent={(event, error) => {
				console.log('=======>keycloak onEvent', event, error);
			}}
			onTokens={(tokens) => {
				console.log('=========>keycloak onTokens', tokens);
			}}
		>
```
...

A login button which triggers keycloak.login as below:
...
```
const LoginWithKeycloak = ({ label, type, onSuccess, onError }) => {
  const { keycloak } = useKeycloak();

  const handleLogin = () => {
    keycloak?.login(
      {
        prompt: 'login',
      }).then(() => {
        if (onSuccess) onSuccess();
      })
      .catch((error) => {
        if (onError) onError(error);
      })
  };
```
...
upon onSuccess it will navigate to next screen

**To Reproduce**

  1. Trigger keycloak.login
  2. Login successfully in InAppWebview keycloak login page
  3. Observe onEvent and onTokens
  4. onEvent was onAuthSuccess and no error
  5. onToken was called but all tokens were undefined

**Expected behavior**
onTokens to return valid tokens instead of undefined

**Screenshots**
Log of events could be captured as below
![image](https://user-images.githubusercontent.com/49872282/133023781-981f2e58-df0e-4185-8200-5be937f601c0.png)

**Smartphone**
- Device: iphone
- OS: 14.5
- Version: 0.5.5

**Comment by IronTony** [comment] 2021-09-14 10:00
Hi,

please check if this issue can help you, I wrote some code for token and the persist.

**Comment by dragons3232** [comment] 2021-09-14 13:11
Hi @IronTony ,
I think you shared a link ? perhaps there is a problem that github removed the link ? Thank you very much for your response by the way

**Comment by IronTony** [comment] 2021-09-14 13:20
Here it is: https://github.com/react-keycloak/react-native-keycloak/issues/18

**Comment by dragons3232** [comment] 2021-09-14 13:43
Thank you very much @IronTony

**Comment by dragons3232** [comment] 2021-09-14 13:51
Well, I already have a persist instance of keycloak client, and it is in top root App. In my onTokens, all tokens are empty, so it is useless for me to save them because they are all invalid.
Perhaps it is an issue on keycloak server. Even though I already checked configuration of client id app on server which enabled "Direct Access Grants", "Service Accounts", "Authorization". I am not sure what else is missing

**Comment by IronTony** [comment] 2021-09-19 09:19
Which version of Keycloak do you have on your server?
Please DM me with your main configuration, during next week  I try to replicate.

**Comment by dragons3232** [comment] 2021-09-22 09:23
Hi @IronTony ,
Thank you very much for you help. It turned out the issue was that keycloak server did not respond correctly with token. We are checking server for problem.

**Comment by IronTony** [comment] 2021-09-22 09:36
Hi @dragons3232, ok nice. Usually quite all the issues are server errors, but I am glad you figured out.
I close the issue, reopen if you need.

Have a nice day

**Closed by IronTony** 2021-09-22 09:36 UTC

**Comment by sm023** [comment] 2022-07-28 07:55
Hi @dragons3232 , 
Did you manage to identify the cause of the problem? 
We are facing a similar issue and it would definitely help us :)

Thank you!
